[window]
padding.x = 8
padding.y = 0
dynamic_title = true
decorations = "Full"

[font]
normal.family = "JetBrains Mono Nerd Font"
normal.style = "Bold"
size = 11

[cursor]
style.shape = "Block"
style.blinking = "On"

[general]
import = [
    "~/.config/alacritty/theme.toml"
]

